### ISSUE TITLE
Is there any suggestion/guidance on how to support a new device with uspi?

### ISSUE THREAD

**Issue by sjtugjy** [rsta2/uspi#28]
Specifically, I need to use a ch340 device attached to rpi3 with a USB interface.

**Comment by rsta2** [comment]
There is no special support for developing drivers for new USB devices with USPi. I can only suggest to take an existing driver (e.g. lib/usbmidi.c) and modify it for your purpose. You will need the information, which USB descriptors and endpoints are available in your target device. If you have specific questions in the development, you can ask them here.

**Comment by sjtugjy** [comment]
Thank you! I have written the driver based on the framework provided by you.
