### ISSUE TITLE
Newbie question about porting

### ISSUE THREAD

**Issue by lonnietc** [rsta2/uspi#33]
Hello All,

I am working on a bare metal project for the x86_64 platform and am wondering if this library could be ported to that platform as well since it seems to have all of the functionality that I need, but is currently on for my platform.

Any thoughts for suggestions would be greatly appreciated.
Thanks in advance

**Comment by rsta2** [comment]
Are you sure, your target platform uses a DWC OTG USB controller, which is the only supported controller by USPi? Otherwise this library won't be of much use for you.

**Comment by rsta2** [comment]
This issue is not really USPi related and there was no further reaction from its originator for over a year. I think, it can be closed.
