### ISSUE TITLE
Need to enable MAC_RX_VLAN_FSE

### ISSUE THREAD

**Issue by fabriziobertocci** [rsta2/uspi#34]
In `lan7800.c` the MAX_RX_FRAME_SIZE is currently set to match the default of the Microchip LAN7800 data sheet (1518 bytes). 

It is my understanding that the value 1518 is calculated as:
```
#define MAX_RX_FRAME_SIZE		(2*6 + 2 + 1500 + 4)
```
That is 2 MAC address (src+dst): 6 bytes + 2 bytes (Ethertype) + 4 bytes for ???

I thought the last 4 bytes were there to include the 4 bytes of a 802.1Q tag, but I suspect this is to include the ending checksum of the frame.

I have a test case where I use VLAN and ssh key exchange fails because a packet long 1518 bytes is dropped.

After looking in the LAN7800 data sheet, I have discovered that the chipset have a feature called FSE (Frame Size Enforcement) that (according to the spec) controllable through the `MAC_RX` register:
```
0: Abort all frames larger than the maximum frame size.
1: Abort all non-VLAN frames larger than maximum frame size. Abort all
frames with a single VLAN tag that are larger the maximum frame size + 4.
Abort all frames with two VLAN tags that are larger than the maximum frame
size + 8.
```
In lan7800.c, line 450, where the RX path is initialized, we should also enable FSE so the Max frame size gets automatically increased for 802.1Q tags.

The fix is quite easy, just add the flag MAC_RX_VLAN_FSE:
```
        // enable RX
	if (   !LAN7800DeviceReadWriteReg (pThis, MAC_RX,
					   (MAX_RX_FRAME_SIZE << MAC_RX_MAX_SIZE_SHIFT) | MAC_RX_RXEN | MAC_RX_VLAN_FSE,
					   ~MAC_RX_MAX_SIZE_MASK) 
```
After adding this flag the driver was able to complete the ssh key exchange with VLAN enabled.

**Comment by rsta2** [comment]
I have added the `MAC_RX_VLAN_FSE` flag as suggested. Thanks!

Yes, the trailing 4 bytes are for the checksum.
